import React from 'react'

const About = () => {
    return (
        <div className="container">
            <h1 className="text-center m-2 p-2">About us</h1>
            <h3 className="text-center">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quidem eum architecto dolorum vitae amet atque ipsa at, cupiditate provident perferendis ipsam, accusamus fuga, incidunt in? Eveniet aperiam amet quaerat? Quaerat suscipit eum explicabo consequuntur debitis enim saepe, consectetur voluptatem pariatur doloribus qui cupiditate, veniam, quisquam ullam quibusdam perspiciatis iste. Sunt dolore quasi minima assumenda tenetur dolorum itaque, tempore iste adipisci illum quas, omnis odit expedita, placeat rerum aut eveniet maiores necessitatibus quaerat tempora. Deserunt veniam eligendi, ipsa fugit similique neque, laborum enim voluptas est explicabo soluta accusamus a, perferendis labore! Possimus, nisi itaque incidunt soluta officiis pariatur accusantium illo molestiae a! Nobis culpa consequuntur eaque ut est veritatis mollitia facilis excepturi ab expedita amet dolorum quibusdam ipsam voluptates eveniet, saepe in! Iste porro optio, necessitatibus soluta sunt rerum consectetur. Sequi quo eum fugit asperiores adipisci quam a nihil commodi omnis, et voluptas, sunt earum animi officia soluta incidunt mollitia sint ullam alias placeat! Molestias in itaque recusandae vitae nobis aspernatur cumque eaque exercitationem minus maiores animi iure, beatae corrupti, dicta, tempore maxime libero magnam? Quia officia id tempora illum, perspiciatis vero, esse doloremque consequuntur voluptatibus saepe in fugiat aperiam explicabo assumenda dolor obcaecati, corporis quo! Assumenda dolore maiores quidem et, adipisci rerum, eligendi dolorem sunt voluptatibus, quasi officia? Molestias labore rem voluptates eius. Reprehenderit soluta voluptate ex? Molestiae numquam nam, sunt maxime hic obcaecati reiciendis dicta dolorum minus porro illo nulla non labore laudantium! Inventore quibusdam vero ut culpa fugiat? Laudantium iure neque eligendi! Id beatae tempore sequi vero quibusdam in vel quo, amet repellendus a odit ipsam veritatis minima accusamus nemo eos reiciendis magnam ratione doloribus impedit vitae. Esse itaque sit eveniet suscipit iste tempore autem earum quibusdam aliquam, perspiciatis culpa qui quisquam unde optio laborum voluptas dolor. Reiciendis voluptatum, consequatur corrupti assumenda voluptates esse nemo quia nobis unde.</h3>
        </div>
    )
}

export default About
