export const ALL_MOVIE_REQUEST = "ALL_MOVIE_REQUEST";
export const ALL_MOVIE_SUCCESS = "ALL_MOVIE_SUCCESS";
export const ALL_MOVIE_FAIL = "ALL_MOVIE_FAIL";

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_FAIL = "MOVIE_DETAILS_FAIL";

export const MOVIE_REVIEWS_REQUEST = "MOVIE_REVIEWS_REQUEST";
export const MOVIE_REVIEWS_SUCCESS = "MOVIE_REVIEWS_SUCCESS";
export const MOVIE_REVIEWS_FAIL = "MOVIE_REVIEWS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";